name       : perl-carp-clan
version    : 6.06
release    : 2
source     :
    - http://search.cpan.org/CPAN/authors/id/K/KE/KENTNL/Carp-Clan-6.06.tar.gz : ea4ac8f611354756d43cb369880032901e9cc4cc7e0bebb7b647186dac00c9d4
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Reports errors from the perspective of the caller of a "clan" of modules,
    similar to "Carp.pm" itself.
description: |
    This module reports errors from the perspective of the caller of a "clan" of modules, similar to "Carp.pm" itself. But instead of giving it a number of levels to skip on the calling stack, you give it a pattern to characterize the package names of the "clan" of modules which shall never be blamed for any error.
builddeps  :
    - perl-sub-uplevel
    - perl-test-exception
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
