name       : perl-carp-clan
version    : '6.08'
release    : 5
source     :
    - https://cpan.metacpan.org/authors/id/E/ET/ETHER/Carp-Clan-6.08.tar.gz : c75f92e34422cc5a65ab05d155842b701452434e9aefb649d6e2289c47ef6708
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Reports errors from the perspective of the caller of a "clan" of modules, similar to "Carp.pm" itself
description: |
    This module reports errors from the perspective of the caller of a "clan" of modules, similar to "Carp.pm" itself. But instead of giving it a number of levels to skip on the calling stack, you give it a pattern to characterize the package names of the "clan" of modules which shall never be blamed for any error.
builddeps  :
    - perl-sub-uplevel
    - perl-test-exception
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
